### ISSUE TITLE
Сообщение об ошибке при корректном ходе игры на сервере

### ISSUE THREAD

**Issue by protsenkovi** [SashkaShashka/Programming_technologies_lab2#2]
Если ввести камень/ножницы/бумага до подключения второго клиента, игра на сервере после подключения второго клиента проходит корректно, но клиенты завершают работу аварийно. 

Если ввести на одном из клиентов выбор некорректно (амень), подключить второго клиента и повторить корректный ввод на обоих - аварийно завершиться только один клиент.

**Comment by SashkaShashka** [comment]
Исправлено
