### ISSUE TITLE
Поведение клиента при повторном подключении

### ISSUE THREAD

**Issue by protsenkovi** [SashkaShashka/Programming_technologies_lab2#4]
При аварийном отключении клиента от сервера и повторном подключении клиент ожидает другого игрока, но при ходе второго игрока всегда завершается аварийно.

Как должен вести себя клиент при повторном подключении: вылетать с ошибкой или успешно переподключиться для завершения игры?

**Comment by SashkaShashka** [comment]
Исправлено
При повторном подключении клиент становится новым клиентом, но сервер обрабатывает одну игру на два игрока, поэтому новому игроку отказано в доступе с сообщением: "С вами тут играть не хотят".
