### ISSUE TITLE
Другие вопросы

### ISSUE THREAD

**Issue by protsenkovi** [SashkaShashka/Programming_technologies_lab2#5]
1.  Почему запрос от клиентов обрабатывается асинхронно, а ответ отправляется в порядке подключения клиентов к серверу? Можно ли избавиться от асинхронного кода?
2. Можно ли сделать рефакторинг функции send_message так, чтобы отправка всех сообщений клиентам выполнялась через неё? Если нет, то почему?

**Comment by SashkaShashka** [comment]
1. Запросы клиентов обрабатываются асинхронно исключительно для того чтобы была возможность написать клиенту сразу после его хода "Ваш ход принят, ждите пока соперник ответит". Можно было избавиться от асинхронного кода и сначала полностью принять корректный ход от первого игрока, затем от второго, но тогда второму придётся ждать пока ответит первый игрок без возможности сделать свой ход. А так оба игрока могут сделать ход, не дожидаясь другого и уйти пить чай, затем вернуться и узнать результаты.
Отсылка ответа сервером происходит в порядке подключения последовательно, так как клиентов всего два и оба игрока эти сообщения получат мгновенно - нет необходимости отправлять их асинхронно. Вот если бы игроков было несколько тысяч и пересылка занимала много времени, то был бы смысл подумать над параллельной отправкой сообщений игрокам.
2. Когда мы в конце отправляем сообщения о ходе противника и исходе игры с помощью send_message, серверу уже не важно, дошли они до клиента или нет, его работа от этого никак не изменится (он на этом этапе уже не будет больше ничего от клиентов принимать). Если клиент аварийно отключился - ему тоже всё равно, дошло ли это сообщение от сервера до него. Таким образом мы можем абсолютно спокойно навешивать в эксепте просто вывод ошибки и факта, что сообщение не получилось отправить. А вот если использовать эту же функцию в асинхронном коде, то тогда свойство безнаказанности от неотправки сообщения теряется, так как в асинхронном блоке активно ведётся переписка клиента и сервера.
